import React from "react";
import { ToastContainer } from "react-toastify";
import { GeneralProvider } from "../context/GeneralContext";
import 'react-toastify/dist/ReactToastify.css';
import "./globals.css";
import { SocketProvider } from "@/hooks/useSocket";

export const metadata = {
  title: "Ticket Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <GeneralProvider>
        <SocketProvider>
          <body className="min-h-screen">
          <ToastContainer />
          {children}</body>
        </SocketProvider>
      </GeneralProvider>
    </html>
  );
}
